image: node:10

stages:
  - test-backend

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  MYSQL_DATABASE: writer_test
  MYSQL_USER: writer
  MYSQL_PASSWORD: writer

cache:
  paths:
  - node_modules/
  - frontend/node_modules

test-backend:
  stage: test-backend
  services:
    - mariadb:10
  script:
    - npm i
    - npm test
